# Generated by Django 3.0.3 on 2020-03-07 12:46

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, max_length=254)),
                ('birthday', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, default='Portugal', max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('nIF', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 9', regex='^.{9}$')])),
                ('saldo', models.CharField(blank=True, default='0', max_length=255)),
                ('divida', models.CharField(blank=True, default='0', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('Boat', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Boat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('driver', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Driver')),
                ('instructor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.instructor')),
                ('modalidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('driver', models.BooleanField(default=False)),
                ('instructor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 46, 6, 338113))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 3, 7, 12, 46, 6, 338135))),
                ('price', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('Boat', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Boat')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('driver', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Driver')),
                ('instructor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='clients.instructor')),
                ('modalidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Modalidade')),
            ],
        ),
    ]
