# Generated by Django 3.0.3 on 2020-03-15 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20200315_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='grades',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 16, 44, 46, 672642)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 16, 44, 46, 672615)),
        ),
    ]
