# Generated by Django 3.0.3 on 2020-04-16 14:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20200416_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 14, 29, 40, 7217)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 14, 29, 40, 7195)),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(default='teste', on_delete=django.db.models.deletion.CASCADE, to='clients.instructor'),
        ),
    ]
