# Generated by Django 3.0.3 on 2020-05-08 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_auto_20200508_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='desconto',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='divida',
            field=models.IntegerField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='saldo',
            field=models.IntegerField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 17, 56, 12, 1833)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 17, 56, 12, 1806, tzinfo=utc)),
        ),
    ]
