# Generated by Django 3.0.3 on 2020-05-13 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0049_auto_20200513_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Boat',
            new_name='boat',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 18, 25, 41, 681976)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 18, 25, 41, 681957)),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Instructor'),
        ),
    ]
